[program:nginx]
command=/usr/local/bin/nginx-entrypoint.sh
environment=BACKEND="127.0.0.1:8000",SOCKETIO="127.0.0.1:9000",FRAPPE_SITE_NAME_HEADER="$host",UPSTREAM_REAL_IP_ADDRESS="127.0.0.1",UPSTREAM_REAL_IP_HEADER="X-Forwarded-For",UPSTREAM_REAL_IP_RECURSIVE="off"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gunicorn]
command=/home/frappe/frappe-bench/env/bin/gunicorn --chdir=/home/frappe/frappe-bench/sites --bind=127.0.0.1:8000 --threads=4 --workers=2 --worker-class=gthread --worker-tmp-dir=/dev/shm --timeout=120 --preload frappe.app:application
user=frappe
directory=/home/frappe/frappe-bench
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:socketio]
command=node /home/frappe/frappe-bench/apps/frappe/socketio.js
user=frappe
directory=/home/frappe/frappe-bench
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=bench worker --queue long,default,short
user=frappe
directory=/home/frappe/frappe-bench
environment=PATH="/home/frappe/.local/bin:/home/frappe/frappe-bench/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=bench schedule
user=frappe
directory=/home/frappe/frappe-bench
environment=PATH="/home/frappe/.local/bin:/home/frappe/frappe-bench/env/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
